version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data.db:/app/data.db
    environment:
      - APP_ENV=production
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data.db:/data.db
